from AVL1 import AVL
from BST1 import BST
import time
def main():
    print('BST TREE')
    l=BST()
    print('Insert n=1000 = ',end='')
    start_time=time.time()
    l.insert(1000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Insert n=10000 = ',end='')
    start_time=time.time()
    l.insert(10000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Insert n=100000 = ',end='')
    start_time=time.time()
    l.insert(100000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Search n=1000 = ',end='')
    start_time=time.time()
    l.search(1000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Search n=10000 = ',end='')
    start_time=time.time()
    l.search(10000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Search n=100000 = ',end='')
    start_time=time.time()
    l.search(100000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Delete n=1000 = ',end='')
    start_time=time.time()
    l.delete(1000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Delete n=10000 = ',end='')
    start_time=time.time()
    l.delete(10000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print()

    print('AVL Tree')
    l=AVL()
    root=None
    print('Insert n=1000 = ',end='')
    start_time=time.time()
    root=l.insertNode(root,1000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Insert n=10000 = ',end='')
    start_time=time.time()
    root=l.insertNode(root,10000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Insert n=100000 = ',end='')
    start_time=time.time()
    root=l.insertNode(root,100000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Search n=1000 = ',end='')
    start_time=time.time()
    l.search(root,1000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Search n=10000 = ',end='')
    start_time=time.time()
    l.search(root,10000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Search n=100000 = ',end='')
    start_time=time.time()
    l.search(root,100000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Delete n=1000 = ',end='')
    start_time=time.time()
    root=l.deleteNode(root,1000)
    print("--- %s seconds ---" % (time.time()-start_time))
    print('Delete n=10000 = ',end='')
    start_time=time.time()
    root=l.deleteNode(root,10000)
    print("--- %s seconds ---" % (time.time()-start_time))

if __name__ == '__main__':
    main()
